spring.application.name=user-service
server.port=8082
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/.well-known/jwks.json

jwt.issuer=http://localhost:8081

spring.datasource.url=jdbc:postgresql://localhost:5432/USER-DB
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:database/migration