#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "$AUTH_DB";
    CREATE DATABASE "$USER_DB";
    CREATE DATABASE "$LISTING_DB";
    CREATE DATABASE "$RECOMMENDATION_DB";
    CREATE DATABASE "$VERIFICATION_DB";
    CREATE DATABASE "$MODERATION_DB";
    CREATE DATABASE "$NOTIFICATION_DB";
    CREATE DATABASE "$CHAT_DB";
EOSQL
