spring.application.name=auth-service
server.port=8081
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/Auth-DB
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:database/migration

jwt.private-key=classpath:keys/private_key.pem
jwt.public-key=classpath:keys/public_key.pem

jwt.issuer=http://localhost:8081
jwt.audience=findmyroomie-api

jwt.access-token-expiration=900000

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email