spring.application.name=api-gateway
server.port=8080

spring.cloud.config.enabled=false

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/.well-known/jwks.json

jwt.issuer=http://localhost:8081
jwt.audience=findmyroomie-api